CREATE TABLE CIGARETTE(
  CIGARETTECODE VARCHAR(20) NOT NULL,
  CIGARETTENAME VARCHAR(50) NOT NULL,
  ISABNORMITY   int         NOT NULL
)


CREATE TABLE ROUTE(
  ORDERDATE DATETIME NOT NULL,
  BATCHNO   INT      NOT NULL,
  ROUTECODE VARCHAR(20) NOT NULL
)


CREATE TABLE SORDER(
  ORDERDATE DATETIME        NOT NULL,
  BATCHNO   INT             NOT NULL,
  ORDERID   VARCHAR(50)     NOT NULL,
  ROUTECODE VARCHAR(20)     NOT NULL,
  ROUTENAME VARCHAR(50)     NOT NULL,
  CUSTOMERCODE VARCHAR(20)  NOT NULL,
  CUSTOMERNAME VARCHAR(100) NOT NULL,
  CIGARETTECODE VARCHAR(20) NOT NULL,
  CIGARETTENAME VARCHAR(50) NOT NULL,
  QUANTITY      INT         NOT NULL,
  SORTID		INT         NOT NULL,
  ADDRESS       varchar(100 not null
)